[package]
name = "rustulator"
version = "0.1.0"
authors = [
    "panicbit <panicbit.dev@gmail.com>",
]
edition = "2018"

[dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.11"
panic-semihosting = "0.5.3"
stm32f3xx-hal = { version = "0.4.0", features = ["stm32f303xc", "rt"] }
bitflags = "1.2.1"
